on:
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Run component test
        run: npm run test-ct
      - name: Bring up the app
        run: npm run start
      - name: Run the endtoend test
        run: npm run e2e-test

